language: node_js
node_js:
- '0.12'
notifications:
  slack: bombbomb:1NGTVbjUegZr88uffaUwizC9
before_install: npm install -g grunt-cli
install: npm install
script:
  - npm test
  - grunt mocha_istanbul